export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const REQUEST_CONVERSATIONS = "REQUEST_CONVERSATIONS";
export const SUCCESS_CONVERSATIONS = "SUCCESS_CONVERSATIONS";
